# Generated by Django 3.2.6 on 2021-08-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectDesign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Product Name', max_length=20, unique=True)),
                ('subtitle', models.CharField(default='Small Description', max_length=50)),
                ('image', models.ImageField(default='default.jpg', upload_to='Products/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
