# Generated by Django 3.2.6 on 2021-08-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectDesign', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='subtitle',
            field=models.CharField(default='Your Ocassion, Our Cakes!', max_length=50),
        ),
    ]
